all: count-safe-practice count-safe count-safe-2-practice count-safe-2

count-safe-practice:
	racket safe-reports.rkt data-practice.txt

count-safe:
	racket safe-reports.rkt data-input.txt

count-safe-2-practice:
	racket safe-reports-2.rkt data-practice.txt

count-safe-2:
	racket safe-reports-2.rkt data-input.txt
