all: distance-practice distance similarity-practice similarity

distance-practice:
	python distance.py data-practice.txt

distance:
	python distance.py data-input.txt

similarity-practice:
	python similarity.py data-practice.txt

similarity:
	python similarity.py data-input.txt
