all: multiply-1-practice multiply-1 multiply-2-practice multiply-2

multiply-1-practice:
	racket multiply-1.rkt data-practice-1.txt

multiply-1:
	racket multiply-1.rkt data-input.txt

multiply-2-practice:
	racket multiply-2.rkt data-practice-2.txt

multiply-2:
	racket multiply-2.rkt data-input.txt


